### ISSUE TITLE
Doc pages return 404 Not Found

### ISSUE THREAD

**Issue by AuroraBorealish** [Kenny2github/mahjong#1]
The manual page linked in the `README.md` (which redirects to https://mahjong.readthedocs.io/zh/latest/) seems to be down

This project seems absolutely incredible and like exactly what I need, but I'm finding it difficult to understand how it's meant to be played through the highly abstracted (and high quality, kudos) code alone.

---

Okay scratch that, before posting I checked the `Wiki` tab and found the [Scratch wiki article](https://en.scratch-wiki.info/wiki/User:Kenny2scratch/Project_Guides/python-mahjong), but I'm still posting this, as you might still want to know the main link in the `README` is down.

Thanks for making this amazing engine!

**Comment by Kenny2github** [comment]
@AuroraBorealish thanks for the report! I've added the GH wiki link in the meantime - RTFD docs have been in progress for a while and the broken link is part of that "progress" lol.

I'm glad you're finding it useful - I created it after realizing that there was somehow *no* library for the purpose on PyPI that I could find. Beware that a 2.0.0 version is in the works (if you ignore the fact that the last commit was 2 years ago - university has sucked out a lot of my time) so what you've made will likely break and you also may not be reading the code that you're using if you use this repo as reference. I can guarantee that the new version will be a lot cleaner (and the docs more useful) once it's done though. And unfortunately it seems right now I'm all you've got :)
